### PR TITLE
Add debian packaging files.

### PR DESCRIPTION
**Pull request by andypugh**
Add Debian packaging files

### CODE REVIEW

**Comment by NTULINUX** [comment]
Does this build the debs properly and have you built and tested LinuxCNC against it? If so, I'll merge it. Thank you andypugh!

**Comment by andypugh** [comment]
I am running through it all from scratch to make sure, but I believe so. 
I should be able to confirm it this evening. 
Setting the local version as rtai-amd64 in menuconfig seems to be necessary to get the debian/configure script to work.

**Comment by NTULINUX** [comment]
Hi andypugh, I noticed this myself. To fix this, I have added a note which fully explains what it is happening in the README.INSTALL file. Not only should the local version be set in the kernel's config, but make deb-pkg command should have LOCALVERSION="" appended to it as well so nothing else gets added to the kernel string.

**Comment by andypugh** [comment]
Yes, I read that, and was wondering if we had found different answers to the same problem

**Comment by NTULINUX** [comment]
If you have any ideas, I'm all ears. What solution did you come up with/propose? Merged btw, thank you andypugh!

**Comment by NTULINUX** [comment]
andypugh, is that ./configure line correct? ./autogen.sh needs to be run before ./configure to generate the Makefiles and configure file. Is this handled by dh_testdir or otherwise internally somehow by Debian's package scripts?

**Comment by andypugh** [comment]
in the RTAI directory I needed to run autogen.sh then ./configure and make menuconfig
then dpkg-buildpackage was able to build debs that appear to work. 

https://github.com/andypugh/RTAI/releases/tag/5.2.2-no-calibration

I won't claim that it compiled 100% cleanly, and signing doesn't work. But I think that is something we handle later.

**Pull request merged**
